title: Dr. Wiebke Schick
logo: "/images/1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Postdoctoral Researcher/Lecturer
  <br>
  <a href="https://ifgi.uni-muenster.de">Institute for Geoinformatics, 
  <br>
  University of Muenster, Germany</a>
  <br><br>
  schickw(at)uni-muenster.de
  <br>
  <a href="/pdfs/cv.pdf">[my CV]</a>
  <br>
  <a href="/publications">[all publications]</a>
  <br><br>
   #(<a href="https://scholar.google.com/citations?user=aetJwkwAAAAJ&hl=de">[Google Scholar]</a>)
  <br>
  <a href="https://orcid.org/0000-0003-2615-8757">[ORCID]</a>
  <br>
theme: jekyll-theme-minimal
google_analytics: UA-104760669-1 # your Google Analytics tracking ID here
